packages:
  - ./

# v10.5+ で有効。依存のビルドを許可するパッケージを列挙
onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
  - '@parcel/watcher'
  - '@biomejs/biome'
  - oxc-parser
  - '@oxc-parser/binding-linux-x64-gnu'

# 余計なプラットフォーム用の optional を入れない
# supportedArchitectures:
#   os:
#     - win32
#     - linux
#   cpu:
#     - x64
#   libc:
#     - glibc
# あるいは、明確に要らないものを無視（例）
# ignoredOptionalDependencies:
#   - '@tailwindcss/oxide-android-arm64'
